In [1]:
# Import

import os, sys
import numpy as np
import scipy as sp
import scipy.linalg as la
import scipy.integrate as integrate
import time

module_path = os.path.abspath(os.path.join(".."))
if module_path not in sys.path:
    sys.path.append(module_path)
from network_control.energies import minimum_input, optimal_input, sim_state_eq, integrate_u, gramian
from network_control.utils import matrix_normalization


In [9]:
N = 20
A = np.random.rand(N,N) - 0.5
A = matrix_normalization(A,"continuous",1e-12)
print(np.real(la.eig(A)[0]))
"""
u,v = la.eig(A)
vi = la.inv(v)
u[0:1] = -1e-1
u[3:4] = -2
A = np.real(np.matmul(np.matmul(v,np.diag(u)),vi))
"""

T = 1
Wc = gramian(A,np.diag(np.random.rand(N)),T,"discrete")

print(Wc - np.matmul(A,np.transpose(A)))

Normalizing A for a continuous-time system
[-0.71997494 -0.71997494 -0.60006478 -0.60006478 -0.51302811 -0.6042004
 -1.55479146 -1.0829941  -1.0829941  -1.28649048 -1.28649048 -0.87320829
 -0.98039882 -0.98039882 -1.39148672 -1.24702763 -1.24702763 -1.20259835
 -1.20259835 -1.08258613]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 